### PR TITLE
Swap backplane with board to match production and build

### PR DESCRIPTION
**Pull request by ahoneybun**
This PR swaps backplane for board to correct name of the component.

### CODE REVIEW

**Comment by leviport** [comment]
I believe both terms are correct for that component. What makes you say that "board" is more correct than "backplane"?

**Comment by ahoneybun** [comment]
> I believe both terms are correct for that component. What makes you say that "board" is more correct than "backplane"?

Production says backplane is incorrect and board is correct, like Thelio Io **board**.

**Comment by leviport** [comment]
This README is obviously out of date, but the old Io board was said to "provide a SATA backplane" here: https://github.com/system76/thelio-io-hardware/blob/master/README.md?plain=1#L5

Since this PCB has the SATA functionality broken out into a standalone component, calling this a "SATA backplane" does not seem incorrect to me. Was there another reason for this change?

**Comment by ahoneybun** [comment]
> This README is obviously out of date, but the old Io board was said to "provide a SATA backplane" here: https://github.com/system76/thelio-io-hardware/blob/master/README.md?plain=1#L5
> 
> Since this PCB has the SATA functionality broken out into a standalone component, calling this a "SATA backplane" does not seem incorrect to me. Was there another reason for this change?

The only reason is that both Production and Build call it SATA board and when backplane is mentioned they do not know what the part is. This is to get everyone on the same page about the component name.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
With respect to the production team, they don't get to unilaterally decide what the products they're building are called.

We are selling this part on the website as a "SATA Backplane":

image

**Comment by ahoneybun** [comment]
Per @s-mcnees this naming comes from the vendor who makes the product and SATA board is used for ordering the product as well. If there are any other issues with this change please reach out to her.

**Comment by jacobgkau** [comment]
> this naming comes from the vendor who makes the product

This is our product, we decide the name, not a vendor.

**Comment by leviport** [comment]
"Board" is a generic word that describes a PCB, so referring to the component as a board does not mean it's the name of the product. A Lemur Pro is a Lemur Pro, but it is often referred to as a "laptop" or a "computer" or a "machine." Thelio Io is frequently referred to as an "Io board," but that's not its name.

I don't think this change is necessary, and I don't think "SATA backplane" was causing any confusion for readers.

**Comment by leviport** [comment]
Per an internal discussion, the official name of the part is SATA Backplane, so I'm going to close this PR.

**Pull request closed without merging**
