### PR TITLE
Make power cord specs more consistent

### PR DESCRIPTION
**Pull request by leviport**
Also fix power cord type on addw1, addw2, and 2070 serw12 (C5 -> C13)

Also change "cable" to "cord" on desktops

### CODE REVIEW

**Comment by XV-02** [comment]
Is this expected to behave broadly as the x11gestures extenions, that is:
- four-touch up/down - switch between workspaces
- four-touch left - open workspaces view
- four-touch right - open application view
or is there other functionality that it should introduce?

**Comment by jacobgkau** [comment]
This isn't quite what we talked about. This still leaves the AC adapter lumped in as a subitem of the DC-in jack specifications. Do you mind if I do the rest, or do you want to discuss it some more?

For reference:

image

The first section is about the port on the laptop; the second section is about the AC adapter; the third section is about the battery. Three separate components that are all connected as parts of the power subsystem.

**Comment by leviport** [comment]
Ah I see what you mean, I didn't realize the first part was describing the laptop's port. That makes a lot of sense though.

>Do you mind if I do the rest

Not at all, thanks for taking over!

**Comment by jacobgkau** [comment]
> I didn't realize the first part was describing the laptop's port.

I've changed `DC-in power` to `DC-in port` on that line to address this confusion.

Samples of the new format:

darp7:
image

kudu6:
image

bonw14:
image

galp5:
image

**Review by jacobgkau — APPROVED** [review]

**Review by storyaddict — APPROVED** [review]
Changes look good. Clean and clear. Thanks @jacobgkau and @leviport

**Pull request merged**
