### PR TITLE
Update OS versions

### PR DESCRIPTION
**Pull request by leviport**

### CODE REVIEW

**Comment by ahoneybun** [comment]
Wouldn't we want to do this with the Massive as well correct?

**Comment by leviport** [comment]
OS versions aren't mentioned in the Massive guides, are they?

**Comment by ahoneybun** [comment]
Should we just have it as Pop!_OS and Ubuntu on both or remove it from the Thelio Major?

**Comment by leviport** [comment]
I've removed the OS sections completely. I think this page will need more lovin' eventually, but this at least gets rid of the inaccurate information as a quick-fix.

**Review by ahoneybun — APPROVED** [review]
LGTM thank you!

**Pull request merged**
