### PR TITLE
Make sidebar easier to read

### PR DESCRIPTION
**Pull request by crawfxrd**
Collapse list so only the models are shown and remove section labels.

Resolves: #122

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
I don't see how this affects #122 very much, but it looks cleaner. Before vs. after:

image

The arrow can be used to open a section manually, or the section opens automatically when navigating into the section (and closes when navigating out of that section).

**Comment by crawfxrd** [comment]
Considering they never explained what they meant, my interpretation was the amount of visual clutter made it hard to tell where each model was.

**Comment by jackpot51** [comment]
We should really remove Components.

**Comment by ctrlcctrlv** [comment]
Thank you, this is what I meant.

**Pull request merged**
